version: '3'
services:
  dbservices:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
    ports:	
      - "3308:3306"
    networks:
      - theatre
  appservice:
    restart: always
    build: .
    depends_on:
      - dbservices
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/microservices?createDatabaseIfNotExist=true
        spring.datasource.username=root
        spring.datasource.password=root
        server.port= 8085
        server.address= 0.0.0.0
    ports:
      - "8085:8081"
    networks:
      - theatre
 
networks:
 theatre: